# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80b56fee7334f44371f3d1ed1a01932bfc6c5b6edf8dfe72c725284a844611f6981944c41c4f720e7a919ae870d7e712f6c27c53b080fdefa0017d566520189

test:
  secret_key_base: 5a789ae834d14693267c03b4f2510d85e8baf766129f58266914584ad861c023fcc816f235646ba637655854cbad32b23065584a2b845286d3ebf12f9987a0e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

